language: java
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "nineclown-github"
    token:
      secure: SONAR_TOKEN
jdk:
 - oraclejdk8

script:
  - sonar-scanner -X

cache:
  directories:
    - '$HOME/.sonar/cache'
