language: java
dist: trusty
sudo: required
jdk:
 - oraclejdk8
install: true
addons:
  sonarcloud:
    organization: nineclown-github
    token:
      secure: SONAR_TOKEN
script:
  ./gradlew clean check sonarqube build
cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle
    
